"""
Management command to seed the database with renewable energy documents
from the original notebook dataset.
"""
import logging

from django.core.management.base import BaseCommand

logger = logging.getLogger(__name__)

# Original documents from the notebook
SEED_DOCUMENTS = [
    {
        "title": "Introduction to Renewable Energy",
        "content": (
            "Renewable energy is derived from natural processes that are "
            "replenished constantly. It includes sources like solar and wind."
        ),
        "metadata": {"year": 2023, "topics": "introduction", "subtopic": "renewable energy"},
    },
    {
        "title": "Solar Power Technology",
        "content": (
            "Solar power harnesses the energy from the sunlight. Advances in "
            "photovoltaic technology have reduced costs significantly."
        ),
        "metadata": {"year": 2023, "topics": "solar power", "subtopic": ""},
    },
    {
        "title": "Wind Energy Generation",
        "content": (
            "Wind energy is generated by converting the kinetic energy of wind "
            "into electricity using turbines."
        ),
        "metadata": {"year": 2023, "topics": "wind energy", "subtopic": ""},
    },
    {
        "title": "Hydroelectric Power",
        "content": (
            "Hydroelectric power uses the flow of water to generate electricity, "
            "and is one of the oldest forms of renewable energy."
        ),
        "metadata": {"year": 2024, "topics": "hydroelectric", "subtopic": ""},
    },
    {
        "title": "Geothermal Energy",
        "content": (
            "Geothermal energy exploits the heat from the earth, offering a "
            "reliable energy source with minimal environmental impact."
        ),
        "metadata": {"year": 2024, "topics": "geothermal", "subtopic": ""},
    },
    {
        "title": "Biomass Energy",
        "content": (
            "Biomass energy comes from organic materials and is considered "
            "renewable when managed sustainably."
        ),
        "metadata": {"year": 2025, "topics": "biomass", "subtopic": ""},
    },
    {
        "title": "Energy Storage Technologies",
        "content": (
            "Energy storage technologies are critical to manage the intermittent "
            "nature of solar and wind energy."
        ),
        "metadata": {"year": 2025, "topics": "energy storage", "subtopic": ""},
    },
    {
        "title": "Renewable Energy and Climate Change",
        "content": (
            "The transition to renewable energy helps reduce greenhouse gas "
            "emissions and mitigate climate change."
        ),
        "metadata": {"year": 2025, "topics": "environment", "subtopic": "policy"},
    },
]

DEFAULT_COLLECTION = "renewable_energy"


class Command(BaseCommand):
    help = "Seed the database with renewable energy documents from the notebook"

    def add_arguments(self, parser):
        parser.add_argument(
            "--no-input",
            action="store_true",
            dest="no_input",
            help="Skip confirmation prompt",
        )
        parser.add_argument(
            "--collection",
            type=str,
            default=DEFAULT_COLLECTION,
            help="Collection name to use (default: renewable_energy)",
        )
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing documents before seeding",
        )

    def handle(self, *args, **options):
        from retriever.models import Collection, Document, DocumentMetadata

        collection_name = options["collection"]
        no_input = options["no_input"]
        clear = options["clear"]

        if not no_input:
            confirm = input(
                f"This will seed {len(SEED_DOCUMENTS)} documents into "
                f"collection '{collection_name}'. Continue? [y/N] "
            )
            if confirm.lower() != "y":
                self.stdout.write(self.style.WARNING("Aborted."))
                return

        # Get or create collection
        collection, created = Collection.objects.get_or_create(
            name=collection_name,
            defaults={
                "description": (
                    "Renewable energy documents covering solar, wind, "
                    "hydroelectric, geothermal, biomass, and energy storage"
                ),
                "embedding_model": "text-embedding-ada-002",
            },
        )

        if created:
            self.stdout.write(
                self.style.SUCCESS(f"Created collection: {collection_name}")
            )
        else:
            self.stdout.write(f"Using existing collection: {collection_name}")

        if clear:
            deleted_count, _ = Document.objects.filter(
                collection=collection
            ).delete()
            self.stdout.write(
                self.style.WARNING(f"Cleared {deleted_count} existing documents")
            )

        # Seed documents
        created_count = 0
        skipped_count = 0

        for doc_data in SEED_DOCUMENTS:
            doc, doc_created = Document.objects.get_or_create(
                title=doc_data["title"],
                collection=collection,
                defaults={
                    "content": doc_data["content"],
                    "metadata_json": doc_data["metadata"],
                    "source": "notebook_seed",
                },
            )

            if doc_created:
                # Create metadata record
                metadata = doc_data["metadata"]
                DocumentMetadata.objects.create(
                    document=doc,
                    year=metadata.get("year"),
                    topics=metadata.get("topics", ""),
                    subtopic=metadata.get("subtopic", ""),
                )
                created_count += 1
                self.stdout.write(f"  Created: {doc_data['title']}")
            else:
                skipped_count += 1
                self.stdout.write(f"  Skipped (exists): {doc_data['title']}")

        # Update collection document count
        collection.document_count = Document.objects.filter(
            collection=collection
        ).count()
        collection.save(update_fields=["document_count"])

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSeeding complete: {created_count} created, "
                f"{skipped_count} skipped. "
                f"Total in collection: {collection.document_count}"
            )
        )

        # Try to index in ChromaDB
        try:
            from retriever.services.vector_store import ChromaDBService

            chroma_service = ChromaDBService()
            documents = Document.objects.filter(collection=collection)
            indexed = chroma_service.index_documents(
                collection_name=collection_name,
                documents=[
                    {
                        "id": str(d.id),
                        "content": d.content,
                        "metadata": d.metadata_json or {},
                    }
                    for d in documents
                ],
            )
            self.stdout.write(
                self.style.SUCCESS(
                    f"Indexed {indexed} documents in ChromaDB"
                )
            )
        except Exception as e:
            self.stdout.write(
                self.style.WARNING(
                    f"Could not index in ChromaDB (will index on first query): {e}"
                )
            )
